DROP TABLE IF EXISTS bid;
DROP TABLE IF EXISTS stock;

CREATE TABLE stock (
  symbol TEXT PRIMARY KEY,
  company TEXT UNIQUE NOT NULL,
  total_count INTEGER NOT NULL,
  price INTEGER NOT NULL
);

CREATE TABLE bid (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  stock_id TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  kind TEXT NOT NULL,
  price INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  note TEXT,
  FOREIGN KEY (stock_id) REFERENCES stock (symbol)
);