sudo: required
dist: trusty

language: python

apt:
  packages:
    - python-dev

python: 3.6

cache:
  directories:
    - $HOME/fplate/.pip-cache/

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install python3-pip
  - sudo apt-get install python-virtualenv

install:
  - python3 -m venv venv
  - source ../venv/bin/activate
  - pip3 install flask codecov

script:
  - coverage run -m pytest

after_success:
  - codecov
  # - bash <(curl -s https://codecov.io/bash)